### ISSUE TITLE
Confirm that category view pagination is working with latest SH404SEF

### ISSUE THREAD

**Issue by ggppdk** [FLEXIcontent/flexicontent-cck#494]
We have reports that category view pagination is not working in when using latest publicily available SH404SEF

Relevant forum thread:
http://www.flexicontent.org/forum/21-troubleshooting/54607-pagination-of-categories-dont-work-properly-with-sh404sef.html

**Comment by Lyquix** [comment]
I am having problems in J 3.4.8 and FC 3.0.14

The URLs don't include the limit parameter so sh404sef is assuming the default list size set in Joomla Global Configuration. If the category has a different Items per Page value, then the pagination links break.

**Comment by ggppdk** [comment]
Ok, so it is confirmed, i will fixed this very soon as this has v3.0.14 milestone,
in 1-2 days will release v3.0.14 closing remaing issues

**Comment by ggppdk** [comment]
Fixed

**Comment by Lyquix** [comment]
@ggppdk : I just updated the sh404sef plugin (/components/com_sh404sef/sef_ext/com_flexicontent.php)  with the file from https://github.com/FLEXIcontent/flexicontent-cck/commit/edaac7918dffca201659b38b8499f656657ccd28 and I still have the pagination bug. The URLs don't include the limit parameter so sh404sef is assuming the default list size set in Joomla Global Configuration. If the category has a different Items per Page value, then the pagination links break or are generated incorrectly.

**Comment by ggppdk** [comment]
Yes, it will not work if you only get the plugin file !!
Yes, they do not include limit

the plugin is not enough there were changes in the files:
**view.html.php**  (category view and legacy views: tags / favourites)

https://github.com/FLEXIcontent/flexicontent-cck/blob/master/site/views/category/view.html.php#L817-L818

```
$_sh404sef = defined('SH404SEF_IS_RUNNING') && JFactory::getConfig()->get('sef');
if ($_sh404sef) $pageNav->setAdditionalUrlParam('limit', $model->getState('limit'));
```

also, besides pagination some other work is needed on the plugin, 
- for category / items we do not use menu-item title

but i think to use menu-item title for views (already testing):
search , directory 
and some other work ...

**Comment by Lyquix** [comment]
Oh sorry I didn't realize that was part of the fix. I will test it today. Thank you!

**Comment by Lyquix** [comment]
Looks great! Thank you!

**Comment by bropa** [comment]
Hi,

i have installed 3.0.14-rc3 and updated the plugin (sef_ext) and it works correct, but only if joomla cache is disabled!?

With enabled cache the urls are fine (/page-1, /page-2, /page-3 …) but content always is from page 1. Any Ideas?

**Comment by ggppdk** [comment]
Normally **limitstart=NN** should be added by the controller task to the safeurlparams
- i am re-opening this, to test that the above is also done for the case of SH404SEF, 

if it is not added then i will fix

**Comment by ggppdk** [comment]
I tested SH404SEF pagination with current 3.0.x-stable branch
- it is working with CACHE ON/OFF with user logged / not logged
just i get links like:

-2.html
instead of
page-2.html

Please test with (in duplicate / localhost site):
https://github.com/FLEXIcontent/flexicontent-cck/tree/3.0.x-stable

Clean your cache and your SH404SEF cache once

**Comment by lyquix-owner** [comment]
This bug has reappeared with Joomla 3.6.2. 
However the cause may be different because sh404sef has the correct URLs including limitstart parameter.
I will do some research today.

**Comment by lyquix-owner** [comment]
Additional info: 

This is unrelated to sh404sef or SEF URLs. I deactivated SEF URLs entirely on the site. Pagination links all display the same page of results:

index.php?option=com_flexicontent&view=category&cid=9&Itemid=137
index.php?option=com_flexicontent&view=category&cid=9&Itemid=137&limitstart=10
index.php?option=com_flexicontent&view=category&cid=9&Itemid=137&limitstart=20
index.php?option=com_flexicontent&view=category&cid=9&Itemid=137&limitstart=30

**Comment by lyquix-owner** [comment]
Using FC 3.1.0-rc. Should I update to 3.1.0-rc2?

**Comment by lyquix-owner** [comment]
Ignore this for a moment. I am unable to reproduce the error in other installations with the same configuration.
